ALTER TABLE IF EXISTS gtin
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;

UPDATE gtin
SET updated_at = TIMESTAMPTZ '2000-01-01T00:00:00Z'
WHERE updated_at IS NULL;

ALTER TABLE IF EXISTS gtin
    ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE IF EXISTS car
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;

UPDATE car
SET updated_at = TIMESTAMPTZ '2000-01-01T00:00:00Z'
WHERE updated_at IS NULL;

ALTER TABLE IF EXISTS car
    ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE IF EXISTS car_mileage
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;

UPDATE car_mileage
SET updated_at = TIMESTAMPTZ '2000-01-01T00:00:00Z'
WHERE updated_at IS NULL;

ALTER TABLE IF EXISTS car_mileage
    ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE IF EXISTS android_app
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;

UPDATE android_app
SET updated_at = TIMESTAMPTZ '2000-01-01T00:00:00Z'
WHERE updated_at IS NULL;

ALTER TABLE IF EXISTS android_app
    ALTER COLUMN updated_at SET NOT NULL;

CREATE TABLE IF NOT EXISTS sync_deletion_event (
    id TEXT PRIMARY KEY,
    domain TEXT NOT NULL,
    resource_id TEXT NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE NOT NULL
);
